---
- name: Ensure the RHINO CA cert, key and host_ssh key exist
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/nebula/{{ item }}"
    owner: root
    group: root
    mode: "0400"
  with_items:
    - ca.crt
    - ca.key
    - nebula_host_ed25519_key
  notify: Restart nebula

- name: Ensure lighthouse cert/key exists
  ansible.builtin.command:
    chdir: /etc/nebula
    cmd: ./nebula-cert sign -name "{{ ansible_hostname }}" -ip "{{ nebula_lighthouse_internal_ip_addr }}/{{ nebula_network_cidr }}" -duration "{{ nebula_client_cert_duration }}"
    creates: "/etc/nebula/{{ ansible_hostname }}.crt"

- name: Add client key directory
  ansible.builtin.file:
    path: /etc/nebula/client-certs
    state: directory
    mode: "0700"
    owner: root
    group: root

- name: Ensure lighthouse config.yml is defined
  ansible.builtin.template:
    src: lighthouse_config.yml.j2
    dest: /etc/nebula/config.yml
    owner: root
    group: root
    mode: "0400"
  notify: Restart nebula

- name: Ensure lighthouse service exists
  ansible.builtin.template:
    src: lighthouse.service.j2
    dest: /etc/systemd/system/lighthouse.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart nebula

- name: Ensure lighthouse service is enabled and running
  ansible.builtin.systemd:
    name: lighthouse
    daemon_reload: true
    enabled: true
    state: started
