---
# Avalanche structure with host networking
# Ports:
#  - avalanchego: 9651 (p2p - public), 9650 (rpc)

- name: Register public ip
  ansible.builtin.uri:
    url: https://ipv4.icanhazip.com/
    return_content: true
  register: public_ip

- name: Create folder structure for data and config
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ folder }}/avalanchego-data"
    - "{{ folder }}/avalanchego-data/offline-prune"
    - "{{ folder }}/avalanchego-config"
    - "{{ folder }}/avalanchego-config/C"

- name: Copy C-Chain config for use
  become: true
  ansible.builtin.copy:
    src: files/C-config.json
    dest: "{{ folder }}/avalanchego-config/C/config.json"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Create a network
  community.docker.docker_network:
    name: "{{ network }}_net"

- name: Run avalanchego container
  community.docker.docker_container:
    name: "{{ execution_container_name }}"
    image: avaplatform/avalanchego:{{ execution_container_version }}
    restart_policy: unless-stopped
    state: started
    stop_timeout: 600
    pull: true
    networks:
      - name: "{{ network }}_net"
    ports:
      # p2p
      - 9651:9651/tcp
      # rpc
      - "{{ nebula_internal_ip_addr }}:9650:9650"
      - 127.0.0.1:9650:9650
    volumes:
      - "{{ folder }}/avalanchego-data:/avalanchego-data"
      - "{{ folder }}/avalanchego-config:/avalanchego-config"
      - /etc/localtime:/etc/localtime:ro
    command:
      - /avalanchego/build/avalanchego
      - --data-dir=/avalanchego-data
      - --chain-config-dir=/avalanchego-config
      - --http-host=0.0.0.0
      - --public-ip={{ public_ip.content | trim }}
      - --staking-port=9651
      - --log-level=info
