---
- name: Update aptos repo for use for setup script
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: "{{ user_dir }}/source/{{ network }}"
    version: main
    update: true
    force: true
    recursive: false

- name: Run/update Aptos prep script
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ user_dir }}/source/{{ network }}"
  with_items:
    - "nice -n 15 ./scripts/dev_setup.sh -b"
  environment:
    PATH: "{{ path }}"
