---
- name: Aleo node init
  hosts: all
  gather_facts: false
  vars_files:
    - "{{ var_file }}"
  tasks:
    - name: Verify build_profile is set
      ansible.builtin.fail:
        msg: build_profile is not set in config. Unable to continue.
      when: not build_profile
  roles:
    - util_rust_install
    - aleo_node_install
    - aleo_node_configure
    - aleo_node_launch
