---
- name: Aptos node init
  hosts: all
  gather_facts: true
  vars:
    ara_playbook_name: aptos node init
    ara_playbook_labels: aptos_init
  vars_files:
    - "{{ var_file }}"

  pre_tasks:
    - name: Verify build_profile is set
      ansible.builtin.fail:
        msg: build_profile is not set in config. Unable to continue.
      when: not build_profile

  roles:
    - aptos_node_dependencies
    - aptos_node_install
    - aptos_node_configure
    - aptos_node_launch
