---
- name: Aptos node upgrade
  hosts: all
  gather_facts: true
  vars:
    ara_playbook_name: aptos node upgrade
    ara_playbook_labels: aptos_upgrade
  vars_files:
    - "{{ var_file }}"

  pre_tasks:
    - name: Verify build_profile is set
      ansible.builtin.fail:
        msg: build_profile is not set in config. Unable to continue.
      when: not build_profile

  roles:
    - aptos_node_dependencies
    - aptos_node_install
    - role: util_ara_configure
      tags:
        - node_upgrade
