---
- name: Aptos node upgrade
  hosts: all
  gather_facts: true
  vars:
    ara_playbook_name: aptos node upgrade
  vars_files:
    - "{{ var_file }}"

  pre_tasks:
    - name: Verify build_profile is set
      ansible.builtin.fail:
        msg: build_profile is not set in config. Unable to continue.
      when: not build_profile

    - name: Record vars for ara
      run_once: true
      delegate_to: localhost
      ara_record:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        type: "{{ item.type }}"
      loop:
        - { key: "aptos_version", value: "{{ node_version }}", type: "text" }

  roles:
    - aptos_node_dependencies
    - aptos_node_install
