---
- name: Aztec Install and Init
  hosts: all
  gather_facts: false
  vars_files:
    - "group_vars/erc20_testnet/testnet_aztec.yml"

  #
  # Var file structure for reference:
  #
  # ---
  # node_version: 0.67.1
  # aztec_config_endpoint: "http://34.82.213.6:8080"
  # ethereum_host: "http://34.19.127.9:8545"

  # container_configs:
  #   - { private_key: "xxxx", validator_number: "00" }
  #   - { private_key: "xxxx", validator_number: "01" }
  #   - { private_key: "xxxx", validator_number: "02" }

  tasks:
    - name: Register public ip
      ansible.builtin.uri:
        url: https://ipv4.icanhazip.com/
        return_content: true
      register: public_ip

    - name: Download config
      ansible.builtin.uri:
        url: "{{ aztec_config_endpoint }}"
        method: POST
        body: '{"jsonrpc":"2.0","method":"node_getNodeInfo","params":[],"id":1}'
        body_format: json
        return_content: true
      register: config

    - name: Assert that valid json returned
      ansible.builtin.assert:
        that:
          - config.json.result.enr is defined
          - config.json.result.l1ContractAddresses.registryAddress is defined
          - config.json.result.l1ContractAddresses.governanceProposerAddress is defined
          - config.json.result.l1ContractAddresses.feeJuiceAddress is defined
          - config.json.result.l1ContractAddresses.rollupAddress is defined
          - config.json.result.l1ContractAddresses.rewardDistributorAddress is defined
          - config.json.result.l1ContractAddresses.governanceAddress is defined
          - config.json.result.l1ContractAddresses.coinIssuerAddress is defined
          - config.json.result.l1ContractAddresses.feeJuicePortalAddress is defined
          - config.json.result.l1ContractAddresses.inboxAddress is defined
          - config.json.result.l1ContractAddresses.outboxAddress is defined

    - name: Start aztec containers
      community.docker.docker_container:
        name: "aztec-{{ item.validator_number }}"
        image: "aztecprotocol/aztec:{{ node_version }}"
        state: started
        restart_policy: unless-stopped
        stop_timeout: 600
        pull: true
        ports:
          - "408{{ item.validator_number }}:408{{ item.validator_number }}/tcp"
          - "408{{ item.validator_number }}:408{{ item.validator_number }}/udp"
          - "90{{ item.validator_number }}:90{{ item.validator_number }}/tcp"
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "{{ user_dir }}/docker-compose/aztec/{{ item.validator_number }}/data:/data"
        env:
          P2P_UDP_ANNOUNCE_ADDR: "{{ public_ip.content | trim }}:408{{ item.validator_number }}"
          P2P_TCP_ANNOUNCE_ADDR: "{{ public_ip.content | trim }}:408{{ item.validator_number }}"
          COINBASE: "0xbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
          VALIDATOR_DISABLED: "false"
          VALIDATOR_PRIVATE_KEY: "{{ item.private_key }}"
          SEQ_PUBLISHER_PRIVATE_KEY: "{{ item.private_key }}"
          L1_PRIVATE_KEY: "{{ item.private_key }}"
          DEBUG: "aztec:*,-aztec:avm_simulator*,-aztec:circuits:artifact_hash,-aztec:libp2p_service,-json-rpc*,-aztec:world-state:database,-aztec:l2_block_stream*"
          LOG_LEVEL: "info"
          AZTEC_PORT: "90{{ item.validator_number }}"
          P2P_ENABLED: "true"
          L1_CHAIN_ID: "1337"
          PROVER_REAL_PROOFS: "true"
          PXE_PROVER_ENABLED: "true"
          ETHEREUM_SLOT_DURATION: "12sec"
          AZTEC_SLOT_DURATION: "36"
          AZTEC_EPOCH_DURATION: "32"
          AZTEC_EPOCH_PROOF_CLAIM_WINDOW_IN_L2_SLOTS: "13"
          ETHEREUM_HOST: "{{ ethereum_host }}"
          BOOTSTRAP_NODES: "{{ config.json.result.enr }}"
          REGISTRY_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.registryAddress }}"
          GOVERNANCE_PROPOSER_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.governanceProposerAddress }}"
          FEE_JUICE_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.feeJuiceAddress }}"
          ROLLUP_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.rollupAddress }}"
          REWARD_DISTRIBUTOR_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.rewardDistributorAddress }}"
          GOVERNANCE_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.governanceAddress }}"
          COIN_ISSUER_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.coinIssuerAddress }}"
          FEE_JUICE_PORTAL_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.feeJuicePortalAddress }}"
          INBOX_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.inboxAddress }}"
          OUTBOX_CONTRACT_ADDRESS: "{{ config.json.result.l1ContractAddresses.outboxAddress }}"
          P2P_UDP_LISTEN_ADDR: "0.0.0.0:408{{ item.validator_number }}"
          P2P_TCP_LISTEN_ADDR: "0.0.0.0:408{{ item.validator_number }}"
          DATA_DIRECTORY: "/data"
        command:
          - start
          - --node
          - --archiver
          - --sequencer
        healthcheck:
          test: ["CMD", "curl", "-fsS", "http://127.0.0.1:90{{ item.validator_number }}/status"]
          interval: 60s
          timeout: 30s
          retries: 10
          start_period: 120s
      loop: "{{ container_configs }}"
