---
- name: Chainlink afn install and configure
  hosts: chainlink-afn-01
  gather_facts: true
  vars_files:
    - "group_vars/mainnets/chainlink_afn.yml"
  vars:
    ara_playbook_name: chainlink_afn
    ara_label_includes: node_upgrade

  roles:
    - util_rust_install
    - chainlink_afn_node_install
    - chainlink_afn_node_configure
    - util_ara_configure
