---
- name: Chainlink support node - Astar blockchain
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/astar.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    - chainlink_support_astar
    - util_docker_prune
