---
- name: Chainlink support node - avalanche
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/avalanche.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    - chainlink_support_avalanche
    - util_docker_prune
