---
- name: Chainlink support node - optimism
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/optimism.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    - chainlink_support_op-stack
    - util_docker_prune
