---
- name: Chainlink version, config and bridge configuration update
  hosts: chainlink-01
  gather_facts: true
  vars_files:
    - "group_vars/mainnets/chainlink.yml"
    - "group_vars/erc20_mainnet/all.yml"
  vars:
    ara_playbook_name: chainlink_ocr
    ara_label_includes: node_upgrade

  roles:
    - util_go_install
    - util_node_install
    - chainlink_node_install
    - chainlink_node_configure
    - chainlink_node_launch
    - util_docker_prune
    - util_ara_configure
