---
- name: Chainlink support node - mantle
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/all.yml"
    - "group_vars/erc20_mainnet/mantle.yml"
  roles:
    - util_docker_install
    - chainlink_support_mantle
    - util_docker_prune
