---
- name: Chainlink support node - Linea geth node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/linea.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    - chainlink_support_linea
    - util_docker_prune
