---
- name: Chainlink support node - BNB Chain
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/bnbchain.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    - chainlink_support_bnbchain
    - util_docker_prune
