---
- name: Chainlink support node - base
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/base.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    # - util_docker_install
    - chainlink_support_op-stack
    - util_docker_prune
