---
- name: Chainlink support node - celo
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/celo.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    - chainlink_support_celo
    - util_docker_prune
