---
- name: Chainlink support node - polygon
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/polygon.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    - chainlink_support_polygon
    - util_docker_prune
