---
- name: Chainlink support node - Scroll blockchain
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/scroll.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    - chainlink_support_scroll
    - util_docker_prune
