---
- name: Chainlink support node - arbitrum nitro
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/arbitrum.yml"
    - "group_vars/erc20_mainnet/all.yml"
  roles:
    - chainlink_support_arbitrum
    - util_docker_prune
