---
- name: Cosmos reconfigure and restart binary
  hosts: all
  gather_facts: true
  vars_files:
    - "{{ var_file }}"
    - "{{ user_file }}"

  pre_tasks:
    - name: Verify we're on the right node
      ansible.builtin.stat:
        path: "{{ user_dir }}/{{ folder }}"
      register: network_folder

    - name: Directory missing
      ansible.builtin.fail:
        msg: "Directory {{ folder }} does not exist. Wrong --limit?"
      when: not network_folder.stat.exists

  roles:
    - cosmos_node_configure
    - cosmos_node_cosmovisor
    - cosmos_node_tools

- name: Restart binaries after reconfigure
  ansible.builtin.import_playbook: cosmos_node_restart_binary.yml
