---
- name: Statesync a node
  hosts: all
  gather_facts: false
  vars_files:
    - "{{ var_file }}"
  vars:
    ara_playbook_name: cosmos statesync
    ara_playbook_labels: cosmos_statesync
    ara_label_includes: cosmos_statesync

  pre_tasks:
    - name: Verify we're on the right node
      ansible.builtin.stat:
        path: "{{ user_dir }}/{{ folder }}"
      register: network_folder

    - name: Directory missing
      ansible.builtin.fail:
        msg: "Directory {{ folder }} does not exist. Wrong --limit?"
      when: not network_folder.stat.exists

  roles:
    - cosmos_node_reset_statesync
    - util_ara_configure
