---
- name: Define hosts
  hosts: localhost
  gather_facts: false
  vars_files:
    - "group_vars/mainnets/{{ target }}.yml"
    - "group_vars/testnets/{{ target }}.yml"
  tasks:
    - name: Check variables
      ansible.builtin.assert:
        that:
          - horcrux_group is defined
          - sentries is defined
        fail_msg: |
          - horcrux_group: "horcrux_group not defined"
          - sentries: "sentries not defined"

    - name: Add all signers
      ansible.builtin.add_host:
        hostname: "{{ item }}"
        group: signers
      loop: "{{ groups[horcrux_group] }}"

- name: Remove Horcrux for chain
  hosts: signers
  become: true
  gather_facts: false
  vars_files:
    - "group_vars/mainnets/{{ target }}.yml"
    - "group_vars/testnets/{{ target }}.yml"
  roles:
    - cosmos_horcrux_remove
