---
# Prepare a target for an upgrade
# ansible-playbook main_cosmos_node_upgrade.yml -i inventory-testnet.ini --limit testnet_juno -e "upgrade_name=v12.0.0 node_version=1.2.3"
- name: Cosmos Node Prep Upgrade
  hosts: all
  gather_facts: true
  vars_files:
    - "{{ var_file }}"
  vars:
    ara_playbook_name: cosmos node upgrade
    ara_playbook_labels: cosmos_upgrade
    ara_label_includes: node_upgrade

  pre_tasks:
    - name: Stat folder
      ansible.builtin.stat:
        path: "{{ user_dir }}/{{ folder }}"
      register: network_folder

    - name: Verify prior to play
      ansible.builtin.assert:
        that:
          - upgrade_name is defined
          - node_version is defined
          - network_folder.stat.exists
        fail_msg: "Upgrade name or version missing or directory {{ folder }} does not exist. Wrong --limit?"

  roles:
    - util_go_install
    - cosmos_node_install
    - cosmos_node_cosmovisor
    - cosmos_node_tools
    - cosmos_node_upgrade
    - util_ara_configure
