---
- name: Cosmos Install and Init
  hosts: all
  gather_facts: true
  vars_files:
    - "{{ var_file }}"
    - "{{ user_file }}"
  roles:
    - util_go_install
    - cosmos_node_install
    - cosmos_node_initialize
    - cosmos_node_configure
    - cosmos_node_cosmovisor
    - cosmos_node_launch
