---
- name: Restart selected cosmovisor binary (with delay for multiple hosts)
  hosts: all
  gather_facts: false
  serial: 1 # Run one host at a time
  vars_files:
    - "{{ var_file }}"

  tasks:
    - name: Restart cosmovisor
      become: true
      ansible.builtin.systemd:
        name: "{{ daemon }}"
        state: restarted

    - name: Wait for RPC response showing at-height
      ansible.builtin.uri:
        url: "http://localhost:{{ custom_port_prefix }}57/status"
        method: GET
        status_code: 200
        return_content: true
      register: rpc_response
      until: rpc_response.content is search(search_string)
      retries: 24
      delay: 15
      vars:
        search_string: '\"catching_up\":false,'
