---
- name: Snapshot a node
  hosts: all
  gather_facts: true
  vars:
    ara_playbook_name: Cosmos take snapshot
    ara_playbook_labels: cosmos_take_snapshot
  vars_files:
    - "{{ var_file }}"

  pre_tasks:
    - name: Verify we're on the right node
      ansible.builtin.stat:
        path: "{{ user_dir }}/{{ folder }}"
      register: network_folder

    - name: Directory missing
      ansible.builtin.fail:
        msg: "Directory {{ folder }} does not exist. Wrong --limit?"
      when: not network_folder.stat.exists

  roles:
    - cosmos_node_tools
    - cosmos_node_take_snapshot
