---
- name: Cosmos Install and Init
  hosts: all
  gather_facts: true
  vars_files:
    - "{{ var_file }}"
    - "{{ user_file }}"

  pre_tasks:
    - name: Verify sudo
      ansible.builtin.shell: "sudo w"
      delegate_to: localhost

  roles:
    - util_go_install
    - cosmos_node_install
    - cosmos_node_initialize
    - cosmos_node_configure
    - cosmos_node_cosmovisor
    - cosmos_node_tools
    - cosmos_node_launch
    - { role: util_zabbix_prepare, become: true }
    - { role: util_zabbix_cosmos_node, become: true }
