---
# Replace the current running binary in directory.  This is used to replace the current running binary with a non-breaking change
# ansible-playbook main_cosmos_node_hotfix.yml -i inventory-testnet.ini --limit testnet_juno"
- name: Deploy hotfix to node
  hosts: all
  gather_facts: true
  vars_files:
    - "{{ var_file }}"
  vars:
    ara_playbook_name: cosmos node hotfix
    ara_playbook_labels: cosmos_hotfix

  pre_tasks:
    - name: Confirm with User
      run_once: true
      ansible.builtin.pause:
        prompt: Please confirm that {{ network }} version {{ node_version }} will replace contents in current directory! Ensure this change is NON-BREAKING! Press return to continue. Press Ctrl+c and then "a" to abort

    - name: Verify we're on the right node
      ansible.builtin.stat:
        path: "{{ user_dir }}/{{ folder }}"
      register: network_folder

    - name: Directory missing
      ansible.builtin.fail:
        msg: "Directory {{ folder }} does not exist. Wrong --limit?"
      when: not network_folder.stat.exists

  roles:
    - util_go_install
    - cosmos_node_install
    - cosmos_node_cosmovisor
    - cosmos_node_tools
    - cosmos_node_hotfix
    - role: util_ara_configure
      tags:
        - node_upgrade

- name: Restart binaries after hotfix
  ansible.builtin.import_playbook: cosmos_node_restart_binary.yml
