---
- name: Cosmos Install and Init
  hosts: all
  gather_facts: true
  vars_files:
    - "{{ var_file }}"
    - "{{ user_file }}"
  vars:
    ara_playbook_name: cosmos init
    ara_playbook_labels: cosmos_init
    ara_label_includes: node_version

  pre_tasks:
    - name: Verify sudo
      ansible.builtin.shell: "sudo w"
      delegate_to: localhost

  roles:
    - util_go_install
    - cosmos_node_install
    - cosmos_node_initialize
    - cosmos_node_configure
    - cosmos_node_cosmovisor
    - cosmos_node_tools
    - cosmos_node_launch
    - util_ara_configure

- name: Install monitoring
  ansible.builtin.import_playbook: util_zabbix_cosmos_node_install.yml
