---
- name: Automatically add persistent peer info on all network nodes
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  vars_files:
    - "{{ var_file }}"
  vars:
    ara_playbook_name: Cosmos local peers
    ara_playbook_labels: cosmos_local_peers

  pre_tasks:
    - name: Verify we're on the right node
      ansible.builtin.stat:
        path: "{{ user_dir }}/{{ folder }}"
      register: network_folder

    - name: Directory missing
      ansible.builtin.fail:
        msg: "Directory {{ folder }} does not exist. Wrong --limit?"
      when: not network_folder.stat.exists

  roles:
    - cosmos_node_local_peers
