---
- name: Base node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/base.yml"
    - "group_vars/erc20_mainnet/all.yml"
  vars:
    ara_playbook_name: base node
    ara_playbook_labels: mainnet

  roles:
    - erc20_op-stack
    - util_docker_prune
    - role: util_ara_configure
      tags: node_upgrade_clel
