---
- name: Omni node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/omni.yml"
  vars:
    ara_playbook_name: omni node
    ara_playbook_labels: mainnet
    ara_label_includes: node_version_clel

  roles:
    - erc20_omni
    - util_docker_prune
    - util_ara_configure
