---
- name: Ethereum sepolia node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_sepolia/sepolia_ethereum.yml"
    - "group_vars/erc20_sepolia/sepolia_all.yml"
  vars:
    ara_playbook_name: ethereum node
    ara_playbook_labels: sepolia
    ara_label_includes: node_upgrade_clel

  roles:
    - erc20_ethereum
    - util_docker_prune
    - util_ara_configure
