---
- name: Polygon node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/polygon.yml"
    - "group_vars/erc20_mainnet/all.yml"
  vars:
    ara_playbook_name: polygon node
    ara_playbook_labels: mainnet
    ara_label_includes: node_version_clel

  roles:
    - erc20_polygon
    - util_docker_prune
    - util_ara_configure
