---
- name: Linea node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/linea.yml"
    - "group_vars/erc20_mainnet/all.yml"
  vars:
    ara_playbook_name: linea node
    ara_playbook_labels: mainnet

  roles:
    - erc20_linea
    - util_docker_prune
    - role: util_ara_configure
      tags: node_upgrade_clel
