---
- name: Gnosis nethermind/lighthouse node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/gnosis.yml"

  vars:
    ara_playbook_name: gnosis node
    ara_playbook_labels: mainnet
    ara_label_includes: node_version_clel

  roles:
    - erc20_gnosis
    - util_docker_prune
    - util_ara_configure
