---
- name: Berachain node - cArtio
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_testnet/testnet_berachain_cartio.yml"
  vars:
    ara_playbook_name: berachain node
    ara_playbook_labels: testnet_cartio
    ara_label_includes: node_upgrade_clel

  roles:
    - erc20_berachain
    - util_docker_prune
    - util_ara_configure
