---
- name: XLayer node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/xlayer.yml"
    - "group_vars/erc20_mainnet/all.yml"
  vars:
    ara_playbook_name: xlayer node
    ara_playbook_labels: mainnet
    ara_label_includes: node_upgrade_clel

  roles:
    - erc20_xlayer
    - util_docker_prune
    - util_ara_configure
