---
- name: Polygon zkEVM node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/polygonzkevm.yml"
    - "group_vars/erc20_mainnet/all.yml"
  vars:
    ara_playbook_name: polygonzkevm node
    ara_playbook_labels: mainnet
    ara_label_includes: node_version_clel

  roles:
    - erc20_polygonzkevm
    - util_docker_prune
    - util_ara_configure
