---
- name: Snapshot an erc20 node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/{{ target }}.yml"
    - "group_vars/erc20_testnet/{{ target }}.yml"
  vars:
    ara_playbook_name: erc20 take snapshot

  pre_tasks:
    - name: Ensure chain exists on source
      become: true
      ansible.builtin.stat:
        path: "{{ execution_snapshot_locations[0] }}"
      register: snapshot_folder

    - name: Directory missing
      ansible.builtin.fail:
        msg: "Directory {{ execution_snapshot_locations }} does not exist. Wrong --limit?"
      when: not snapshot_folder.stat.exists

  roles:
    - erc20_take_snapshot
