---
- name: Chainlink support node - arbitrum sepolia-rollup
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_sepolia/sepolia_arbitrum.yml"
    - "group_vars/erc20_sepolia/sepolia_all.yml"
  vars:
    ara_playbook_name: arbitrum node
    ara_playbook_labels: sepolia

  roles:
    - erc20_arbitrum
    - util_docker_prune
    - role: util_ara_configure
      tags: node_upgrade_clel
