---
- name: Berachain Install and Init
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/berachain.yml"
  vars:
    ara_playbook_name: berachain node
    ara_playbook_labels: mainnet
    ara_label_includes: node_version_clel

  roles:
    - erc20_berachain
    - util_docker_prune
    - util_ara_configure
