---
- name: Chainlink support node - arbitrum sepolia-rollup
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_sepolia/sepolia_arbitrum.yml"
    - "group_vars/erc20_sepolia/sepolia_all.yml"
  vars:
    ara_playbook_name: arbitrum node
    ara_playbook_labels: sepolia
    ara_label_includes: node_upgrade_clel

  roles:
    - erc20_arbitrum
    - util_docker_prune
    - util_ara_configure
