---
- name: Chainlink support node - Astar blockchain
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/astar.yml"
    - "group_vars/erc20_mainnet/all.yml"
  vars:
    ara_playbook_name: astar node
    ara_playbook_labels: mainnet

  roles:
    - erc20_astar
    - util_docker_prune
    - role: util_ara_configure
      tags: node_upgrade_clel
