---
- name: Kroma node
  hosts: all
  gather_facts: true
  vars_files:
    - "group_vars/erc20_mainnet/kroma.yml"
    - "group_vars/erc20_mainnet/all.yml"
  vars:
    ara_playbook_name: kroma node
    ara_playbook_labels: mainnet
    ara_label_includes: node_version_clel

  roles:
    - erc20_op-stack-custom
    - util_docker_prune
    - util_ara_configure
