---
- name: Initial init of bare machines with root-only login
  # Run with -k to provide root password
  hosts: all
  gather_facts: true
  vars_files:
    - "{{ user_file }}"
  become: true
  roles:
    - init_bare_root
