---
# To init a templated vsphere image for use
- name: Initial init of vsphere machines not ready for other playbooks
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Apt update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        autoremove: true
        autoclean: true

  roles:
    - init_vsphere

- name: Reboot if necessary
  ansible.builtin.import_playbook: util_system_reboot.yml
