---
- name: Aptos node init
  hosts: all
  gather_facts: false
  vars_files:
    - "{{ var_file }}"
  roles:
    - aptos_node_dependencies
    - aptos_node_install
    - aptos_node_configure
    - aptos_node_launch
