---
- name: Run setup and secure playbooks
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - "{{ user_file }}"

  pre_tasks:
    - name: Verify local sudo
      become: false
      ansible.builtin.shell: "sudo w"
      delegate_to: localhost

    - name: Confirm with User if missing nebula_internal_ip_addr
      run_once: true
      ansible.builtin.pause:
        prompt: Nebula IP is missing.  Press return to continue. Press Ctrl+c and then "a" to abort
      when: nebula_internal_ip_addr is not defined

  roles:
    - setup
    - secure

- name: Import nebula playbook
  ansible.builtin.import_playbook: util_nebula_install.yml
  when: nebula_internal_ip_addr is defined

- name: Import zabbix playbook
  ansible.builtin.import_playbook: util_zabbix_install.yml
