---
- name: Aptos node upgrade
  hosts: all
  gather_facts: false
  vars_files:
    - "{{ var_file }}"
  roles:
    - aptos_node_dependencies
    - aptos_node_install

  post_tasks:
    - name: Restart service
      become: true
      ansible.builtin.systemd:
        name: "aptos-node"
        daemon_reload: true
        state: restarted
