---
- name: Upgrade Nebula Binary
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - "group_vars/all.yml"
    - "group_vars/users.yml"

  tasks:
    - name: Run install from Nebula playbook
      ansible.builtin.include_role:
        name: util_nebula_install
        tasks_from: install.yml
      when: inventory_hostname in groups['nebula_lighthouse'] or nebula_internal_ip_addr is defined
