---
- name: Install or reinstall ipfs and ipfs-cluster
  hosts: stargaze_api
  gather_facts: true
  roles:
    - { role: util_ipfs_install, when: ipfs_role is defined }
    - { role: util_ipfs_cluster_install, when: ipfs_role is defined }
    - util_docker_install
    - util_imgproxy_install
