- name: Deploy Zabbix
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - "{{ var_file }}"

  pre_tasks:
    - name: Verify sudo
      ansible.builtin.shell: "sudo w"
      delegate_to: localhost

  roles:
    - util_zabbix_prepare
    - util_zabbix_cosmos_node
