---
- name: Create target user
  ansible.builtin.user:
    name: "{{ target_user }}"
    password: "{{ password }}"
    state: present
    shell: /bin/bash

- name: Set authorized key 1
  ansible.posix.authorized_key:
    user: "{{ target_user }}"
    key: "{{ ssh_pubkey1 }}"

- name: Set authorized key 2
  ansible.posix.authorized_key:
    user: "{{ target_user }}"
    key: "{{ ssh_pubkey2 }}"

- name: Install sudo
  ansible.builtin.apt:
    name:
      - sudo
    state: present
    update_cache: false

- name: Allow sudo for target_user
  ansible.builtin.copy:
    content: "{{ target_user }} ALL=(ALL:ALL) NOPASSWD: ALL"
    dest: "/etc/sudoers.d/{{ target_user }}"
    owner: "root"
    group: "root"
    mode: "0440"

- name: Change ansible_user for back to original
  ansible.builtin.set_fact:
    ansible_user: "{{ target_user }}"

- name: Capture files in sudoers for deletion
  ansible.builtin.find:
    paths: "/etc/sudoers.d"
    file_type: file
    excludes:
      - "{{ target_user }}"
      - "README"
  register: found_files

- name: Delete extra users in sudoers
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ found_files['files'] }}"
