---
- name: Force uniform sources.list
  ansible.builtin.template:
    src: sources.list_{{ ansible_distribution_release }}.j2
    dest: "/etc/apt/sources.list"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Apt update and upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
