---
# Linea Support with custom ports (105)
# Ports:
#  - Besu:
#    - 10503 (p2p, public)
#    - 10545 (rpc, internal)

- name: Register public ip
  ansible.builtin.uri:
    url: https://ipv4.icanhazip.com/
    return_content: true
  register: public_ip

- name: Get current user and group
  ansible.builtin.shell:
    cmd: echo "$(id -u):$(id -g)"
  register: current_user

- name: Create Linea folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ folder }}"
    - "{{ folder }}/linea-data"

- name: Create a network
  community.docker.docker_network:
    name: "{{ network }}_net"

# - name: Check if linea has been initialized
#   become: true
#   ansible.builtin.stat:
#     path: "{{ folder }}/linea-data/genesis.json"
#   register: node_initialized

# - name: Initialize node
#   when: not node_initialized.stat.exists
#   block:
#     - name: Download Linea genesis
#       ansible.builtin.get_url:
#         url: "{{ execution_genesis }}"
#         dest: "{{ folder }}/linea-data/genesis.json"
#         mode: "0644"

#     - name: Run geth init container for Linea
#       community.docker.docker_container:
#         name: "{{ execution_container_name }}_init"
#         image: ethereum/client-go:{{ execution_container_version }}
#         state: started
#         stop_timeout: 600
#         pull: true
#         networks:
#           - name: "{{ network }}_net"
#         volumes:
#           - "{{ folder }}/linea-data:/root/.ethereum"
#           - "{{ folder }}/linea-data/genesis.json:/genesis.json:ro"
#           - /etc/timezone:/etc/timezone:ro
#           - /etc/localtime:/etc/localtime:ro
#         command:
#           - init
#           - --datadir=/root/.ethereum
#           - /genesis.json

- name: Run besu container for Linea
  community.docker.docker_container:
    name: "{{ execution_container_name }}"
    image: consensys/linea-besu-package:{{ execution_container_version }}
    state: started
    restart_policy: unless-stopped
    stop_timeout: 600
    pull: true
    user: "{{ current_user.stdout }}"
    networks:
      - name: "{{ network }}_net"
    ports:
      # p2p
      - "{{ custom_port_prefix }}03:{{ custom_port_prefix }}03/tcp"
      - "{{ custom_port_prefix }}03:{{ custom_port_prefix }}03/udp"
      # rpc
      - "{{ nebula_internal_ip_addr }}:{{ custom_port_prefix }}45:8545"
      - "127.0.0.1:{{ custom_port_prefix }}45:8545"
    volumes:
      - "{{ folder }}/linea-data:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # entrypoint:
    #   - /opt/besu/bin/besu
    command:
      # General
      - --data-path=/data
      - --p2p-host={{ public_ip.content | trim }}
      - --p2p-port={{ custom_port_prefix }}03
      - --plugin-linea-l1-rpc-endpoint={{ ethereum_l1 }}
      - --profile=advanced-mainnet
      - --bootnodes={{ execution_bootnodes }}
      - --sync-mode=snap
      - --logging=info
      # RPC
      - --rpc-http-enabled=true
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-cors-origins=*
      - --rpc-http-api=ETH,NET,WEB3,TXPOOL,PLUGINS
      - --rpc-ws-enabled=true
      - --rpc-ws-api=ETH,NET,WEB3,TXPOOL,PLUGINS
      - --rpc-ws-port=8546
      - --rpc-ws-host=0.0.0.0
      # Gas issues during init
      - --tx-pool-min-gas-price=1000
      - --min-gas-price=1000
      # RMN
      # - --rpc.batch-response-max-size=70000000
      - --rpc-tx-feecap=0
