network: chainlink_afn
folder: chainlink_afn
repo: smartcontractkit/risk-management-network-nop-release.git

node_version: 9614ea53b5aee0e06c160deec735a397724e55eb # 11.8.2024
shared_config_version: 6538aa00a0e9420128f9eeacda4ccced942f0a9f # 12.6.2024 - more lanes Base to Ronin

# For generating new keys
node_version_keygen_prep: 9614ea53b5aee0e06c160deec735a397724e55eb
keygen_flags: "--add Ronin"

# Grafana dashboard
dashboardUID: NGatdDfnk
