network: chainlink_afn
folder: chainlink_afn
repo: smartcontractkit/risk-management-network-nop-release.git

node_version: 9614ea53b5aee0e06c160deec735a397724e55eb # 11.8.2024
shared_config_version: 5c01af5487e209647d95da1e8d7dd22ec9f6935f # 02.18.2025

# For generating new keys
node_version_keygen_prep: 9614ea53b5aee0e06c160deec735a397724e55eb
keygen_flags: "--add Ronin"

# Grafana dashboard
dashboardUID: NGatdDfnk
