network: chainlink_afn
folder: chainlink_afn
repo: smartcontractkit/risk-management-network-nop-release.git

node_version: 9614ea53b5aee0e06c160deec735a397724e55eb # 11.8.2024
shared_config_version: 1f96b3e4cf8c999e70c5d1266d23da3f9fffcd63 # 11.21.2024 - remove 1.2 lanes

# For generating new keys
node_version_keygen_prep: 9614ea53b5aee0e06c160deec735a397724e55eb
keygen_flags: "--add Ronin"

# Grafana dashboard
dashboardUID: NGatdDfnk
