network: injective
folder: ".injectived"
daemon: injectived
chain_id: injective-1
#
# BINARY
# Binaries at: https://github.com/InjectiveLabs/injective-chain-releases/releases
node_version: v1.14.1 # BINARY
binary: https://github.com/InjectiveLabs/injective-chain-releases/releases/download/v1.14.1-1740773301/linux-amd64.zip
binary_processing: zip
lib_sidecar: true
#
genesis: https://raw.githubusercontent.com/InjectiveLabs/mainnet-config/master/10001/genesis.json
seeds: "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14356,20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:14356"
app_file: https://raw.githubusercontent.com/InjectiveLabs/mainnet-config/master/10001/app.toml
minimum_gas_price: "500000000inj"
custom_port_prefix: 143

snap_rpc: https://injective-rpc.polkachu.com:443

upgrade_name: v1.14.1
