---
- name: Install smart monitoring
  ansible.builtin.apt:
    name:
      - smartmontools
    state: present

- name: Get node location specifics
  ansible.builtin.uri:
    url: http://ipinfo.io/json
    method: GET
    return_content: true
  register: node_info

- name: Split lat long
  ansible.builtin.set_fact:
    latlong: "{{ node_info.json.loc | split(',') }}"

- name: Capture outdated zabbix repo files
  ansible.builtin.find:
    paths: "/etc/apt/sources.list.d"
    file_type: file
    patterns:
      - "repo_zabbix_com_zabbix_*"
      - "zabbix.sources"
  register: found_files

- name: Delete extra zabbix repos
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ found_files['files'] }}"
