---
# Gnosis Support with custom ports
# Ports:
#  - nethermind: 12203 (p2p), 12245 (rpc)
#  - lighthouse: 12200 (p2p)

- name: Ensure jwtsecret file exists
  ansible.builtin.shell: "set -o pipefail && openssl rand -hex 32 | tr -d '\n' > jwtsecret"
  args:
    chdir: "{{ user_dir }}/docker-compose"
    creates: jwtsecret
    executable: /bin/bash

- name: Ensure folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ folder }}"
    - "{{ folder }}/nethermind"
    - "{{ folder }}/lighthouse"

- name: Create a network
  community.docker.docker_network:
    name: "{{ network }}_net"

- name: Run nethermind container for Gnosis
  community.docker.docker_container:
    name: gnosis_nethermind
    image: nethermind/nethermind:{{ execution_container_version }}
    restart_policy: unless-stopped
    state: started
    stop_timeout: 600
    pull: true
    ports:
      # p2p
      - "{{ custom_port_prefix }}03:{{ custom_port_prefix }}03/tcp"
      - "{{ custom_port_prefix }}03:{{ custom_port_prefix }}03/udp"
      # rpc
      - "{{ nebula_internal_ip_addr }}:{{ custom_port_prefix }}45:8545"
      - 127.0.0.1:{{ custom_port_prefix }}45:8545
    networks:
      - name: "{{ network }}_net"
    volumes:
      - "{{ folder }}/nethermind:/data"
      - "{{ user_dir }}/docker-compose/jwtsecret:/jwtsecret"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config=gnosis
      - --datadir=/data
      - --log=INFO
      - --Sync.SnapSync=false
      - --JsonRpc.Enabled=true
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.Port=8545
      - --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net]
      - --JsonRpc.JwtSecretFile=/jwtsecret
      - --JsonRpc.EngineHost=0.0.0.0
      - --JsonRpc.EnginePort=8551
      - --Network.P2PPort=12203
      - --Network.DiscoveryPort=12203
      - --HealthChecks.Enabled=false
      - --Pruning.CacheMb=2048
      # RMN
      - --JsonRpc.MaxBatchResponseBodySize=70000000 # Per RMN Documentation

- name: Run lighthouse container for Gnosis
  community.docker.docker_container:
    name: gnosis_lighthouse
    image: sigp/lighthouse:{{ consensus_container_version }}
    restart_policy: unless-stopped
    state: started
    stop_timeout: 600
    pull: true
    networks:
      - name: "{{ network }}_net"
    ports:
      # p2p
      - "{{ custom_port_prefix }}00:{{ custom_port_prefix }}00/tcp" # p2p
      - "{{ custom_port_prefix }}00:{{ custom_port_prefix }}00/udp" # p2p
    volumes:
      - "{{ folder }}/lighthouse:/data"
      - "{{ user_dir }}/docker-compose/jwtsecret:/jwtsecret"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - /usr/local/bin/lighthouse
      - beacon_node
      - --network=gnosis
      - --disable-upnp
      - --datadir=/data
      - --port={{ custom_port_prefix }}00
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --execution-endpoint=http://gnosis_nethermind:8551
      - --execution-jwt=/jwtsecret
      - --checkpoint-sync-url=https://checkpoint.gnosischain.com/
