---
- name: Initialize node
  ansible.builtin.include_tasks: init_node.yml

- name: Run node
  ansible.builtin.include_tasks: run_node.yml

- name: Run Oracle
  when: (validator is defined) and (validator)
  ansible.builtin.include_tasks: run_oracle.yml
