util_ara_configure_new_labels: >-
  [
    "network:{{ network }}",
    "{{ network }}_el_version:{{ execution_container_version }}"
    {%- if consensus_container_version is defined and consensus_container_version -%}
    , "{{ network }}_cl_version:{{ consensus_container_version }}"
    {%- endif -%}
  ]
