- name: Open range of ufw ports for p2p traffic
  community.general.ufw:
    rule: allow
    port: 8000:8020
    proto: "{{ item.proto }}"
    comment: "External: Agave p2p ports"
  loop:
    - { proto: tcp }
    - { proto: udp }

- name: Copy service file
  become: true
  ansible.builtin.template:
    src: "agave-validator.service.j2"
    dest: "/etc/systemd/system/agave-validator.service"
    owner: root
    group: root
    mode: "0644"
  notify: Restart agave

- name: Copy logrotate file
  become: true
  ansible.builtin.template:
    src: "agave-validator.logrotate.j2"
    dest: "/etc/logrotate.d/agave-validator"
    owner: root
    group: root
    mode: "0644"
  notify: Restart logrotate

- name: Enable agave-validator service
  become: true
  ansible.builtin.systemd:
    name: agave-validator
    daemon_reload: true
    enabled: true
    state: started
