---
- name: Install caddy repository key
  become: true
  ansible.builtin.get_url:
    url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
    dest: /usr/share/keyrings/caddy.asc
    mode: "0644"
    force: true

- name: Install caddy repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - "deb [signed-by=/usr/share/keyrings/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    - "deb-src [signed-by=/usr/share/keyrings/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"

- name: Install caddy components
  become: true
  ansible.builtin.apt:
    name:
      - caddy
    state: present

- name: Open http ports in ufw
  become: true
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
    comment: External - Caddy
  loop:
    - 80
    - 443
