# EVM Devnet
network: sei
folder: ".sei"
daemon: seid
chain_id: "arctic-1"
node_version: v6.0.2
repo: https://github.com/sei-protocol/sei-chain
genesis: https://raw.githubusercontent.com/sei-protocol/testnet/main/arctic-1/genesis.json
custom_port_prefix: 119
peers: "836213055dc975fe93acd97a21ba3ad3bc8a2985@3.20.239.96:26656,cce0882a656cd97c6bac7f0f0bc04139a3d390f3@3.145.4.178:26656"
minimum_gas_price: "0.02usei"

# Tendermint config version
tendermint_config_version: 37

snap_rpc: https://rpc.arctic-1.seinetwork.io:443

snapshot_url: https://snapshots.rhinostake.com/testnet-sei/sei-snapshot.38198047.tar.lz4

upgrade_name: v6.0.2

p2p_state_sync: true
