network: union
folder: ".union"
daemon: uniond
chain_id: "union-testnet-9"
node_version: v0.25.0
repo: https://github.com/unionlabs/union.git
# Binary processing
# binary: https://share.rhinostake.com/uniond-v0.25.0
#binary_processing: targz
# binary_name: uniond-v0.25.0

genesis: "https://raw.githubusercontent.com/unionlabs/union/refs/heads/main/networks/genesis/union-testnet-9/genesis.json"
seeds: "c2bf0d5b2ad3a1df0f4e9cc32debffa239c0af90@testnet.seed.poisonphang.com:26656,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@testnet-seeds.polkachu.com:24656"
custom_port_prefix: 246
minimum_gas_price: "0muno"

snap_rpc: https://rpc.testnet.seed.poisonphang.com:443
# upgrade_name: v0.24.0
