---
- name: Clone horcrux repo
  ansible.builtin.git:
    repo: "{{ horcrux_repo }}"
    dest: "{{ user_dir }}/source/horcrux"
    version: "{{ horcrux_version }}"
    update: true
    force: true
    recursive: true
  register: horcrux

- name: Build horcrux
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ user_dir }}/source/horcrux"
  with_items:
    - "make install"
  environment:
    PATH: "{{ path }}"
    GOPATH: "{{ user_dir }}/go"

- name: Move to /usr/local/bin
  become: true
  ansible.builtin.copy:
    src: "{{ user_dir }}/go/bin/horcrux"
    dest: /usr/local/bin/horcrux
    owner: root
    group: root
    mode: "0755"
    remote_src: true
