network: aptos
folder: testnet
repo: https://github.com/aptos-labs/aptos-core
node_version: 255673e8f2757ed8634a7d65d7aca11de7016cde # aptos-node-v1.27.0-rc
genesis_blob: https://raw.githubusercontent.com/aptos-labs/aptos-networks/main/testnet/genesis.blob
waypoint: https://raw.githubusercontent.com/aptos-labs/aptos-networks/main/testnet/waypoint.txt
p2p_port: 6180
p2p_port_vfn: 6182
api_port: 8080

# Build profile
build_profile: release

# Grafana dashboard
dashboardUID: bz8kPr673
# hotfix_binary_url:
