---
- name: Register public ip
  ansible.builtin.uri:
    url: https://ipv4.icanhazip.com/
    return_content: true
  register: public_ip

#
## Configure beacond
#
- name: Download latest config.toml and app.toml files from source
  become: true
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "{{ folder }}/{{ consensus_container_name }}/config/{{ item | basename }}"
    mode: "0644"
  loop:
    - "{{ consensus_config_toml }}"
    - "{{ consensus_app_toml }}"

# Configure components:
- name: Update config.toml and app.toml
  become: true
  block:
    # Configure config.toml components:
    - name: Update options in config.toml
      community.general.ini_file:
        path: "{{ folder }}/{{ consensus_container_name }}/config/config.toml"
        section: "{{ item.section }}"
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        create: false
      loop:
        - { section: "", key: "moniker", value: '"{{ network }}"' }
        - { section: "p2p", key: "laddr", value: '"tcp://0.0.0.0:{{ custom_port_prefix }}56"' }
        - {
            section: "p2p",
            key: "external_address",
            value: '"{{ public_ip.content | trim }}:{{ custom_port_prefix }}56"',
          }
        - { section: "p2p", key: "seeds", value: '"{{ consensus_seeds | default("") }}"' }
        - { section: "p2p", key: "persistent_peers", value: '"{{ consensus_persistent_peers | default("") }}"' }
        - { section: "p2p", key: "max_num_inbound_peers", value: "37" }
        - { section: "p2p", key: "max_num_outbound_peers", value: "27" }
        - { section: "rpc", key: "laddr", value: '"tcp://0.0.0.0:26657"' }

    # Configure app.toml components:
    - name: Update options in app.toml
      community.general.ini_file:
        path: "{{ folder }}/{{ consensus_container_name }}/config/app.toml"
        section: "{{ item.section }}"
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        create: false
      loop:
        - { section: "", key: "pruning", value: '"everything"' }
        - { section: "telemetry", key: "prometheus-retention-time", value: '"60"' }
        - { section: "beacon-kit.engine", key: "rpc-dial-url", value: '"http://{{ execution_container_name }}:8551"' }
        - { section: "beacon-kit.engine", key: "jwt-secret-path", value: '"/jwtsecret"' }
        - { section: "beacon-kit.kzg", key: "trusted-setup-path", value: '"/beacond/kzg-trusted-setup.json"' }
        - {
            section: "beacon-kit.payload-builder",
            key: "suggested-fee-recipient",
            value: '"{{ suggested_fee_recipient | default("0x0000000000000000000000000000000000000000") }}"',
          }
        - { section: "beacon-kit.block-store-service", key: "enabled", value: '"false"' }
        - { section: "beacon-kit.node-api", key: "enabled", value: '"true"' }
        - { section: "beacon-kit.node-api", key: "address", value: '"0.0.0.0:3500"' }
