---
- name: Initialize node
  ansible.builtin.include_tasks: init_node.yml

- name: Configure node
  ansible.builtin.include_tasks: configure_node.yml

- name: Run node
  ansible.builtin.include_tasks: run_node.yml
