- name: Update network interfaces for devices with dual static IPs
  ansible.builtin.template:
    src: interfaces-dual.j2
    dest: "/etc/network/interfaces"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - internal_ip is defined
    - external_ip is defined

- name: Update network interfaces for devices when just internal IP
  ansible.builtin.template:
    src: interfaces-internalOnly.j2
    dest: "/etc/network/interfaces"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - internal_ip is defined
    - external_ip is not defined

- name: Install resolvconf to force external DNS servers
  ansible.builtin.apt:
    name:
      - resolvconf
    state: present
    update_cache: false

- name: Uniform sources.list
  ansible.builtin.include_role:
    name: init_bare
    tasks_from: update_sources.yml

- name: Apt update and upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
    cache_valid_time: 3600
