---
# Prysm/erigon support structure for Holesky
# Prysm: 13000/tcp, 12000/udp for p2p, 3500 rpc
# Erigon: 30303/tcp/udp, 42069/tcp, 8545 rpc, 8546 ws

- name: Register public ip
  ansible.builtin.uri:
    url: https://ipv4.icanhazip.com/
    return_content: true
  register: public_ip

- name: Add docker-compose and docker-data folders
  ansible.builtin.shell: "openssl rand -hex 32 | tr -d '\n' > jwtsecret"
  args:
    chdir: "{{ user_dir }}/docker-compose"
    creates: jwtsecret
    executable: /bin/bash

- name: Create a network
  community.docker.docker_network:
    name: goerli_net

- name: Create erigon-data folder
  become: true
  ansible.builtin.file:
    path: "{{ user_dir }}/docker-compose/erigon-data"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Get current user and group
  ansible.builtin.shell:
    cmd: echo "$(id -u):$(id -g)"
  register: current_user

- name: Run erigon container
  community.docker.docker_container:
    name: erigon
    image: thorax/erigon:2.60.8
    restart_policy: unless-stopped
    state: started
    pull: true
    stop_timeout: 600
    user: "{{ current_user.stdout }}"
    networks:
      - name: goerli_net
    ports:
      # p2p
      - 30303:30303/tcp
      - 30303:30303/udp
      # rpc
      - "{{ nebula_internal_ip_addr }}:8545:8545"
      - 127.0.0.1:8545:8545
      - "{{ nebula_internal_ip_addr }}:8546:8546"
      - 127.0.0.1:8546:8546
    volumes:
      - "{{ user_dir }}/docker-compose/erigon-data:/erigon-data"
      - "{{ user_dir }}/docker-compose/jwtsecret:/erigon-data/jwtsecret"
    command:
      - --chain=holesky
      - --datadir=/erigon-data
      - --port=30303
      - --nat=extip:{{ public_ip.content | trim }}
      # RPC
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/erigon-data/jwtsecret
      - --torrent.port=42069
      - --private.api.addr=127.0.0.1:9090
      - --http
      - --ws
      - --http.api=eth,debug,net,trace,web3,erigon

- name: Run prysm container
  community.docker.docker_container:
    name: prysm
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    restart_policy: unless-stopped
    state: started
    pull: true
    stop_timeout: 600
    networks:
      - name: goerli_net
    ports:
      # p2p
      - 13000:13000/tcp
      - 12000:12000/udp
      # rpc
      - "{{ nebula_internal_ip_addr }}:3500:3500"
      - 127.0.0.1:3500:3500
      # - 12500:3500
    volumes:
      - "{{ user_dir }}/docker-compose/prysm/data:/data"
      - "{{ user_dir }}/docker-compose/jwtsecret:/jwtsecret"
    command:
      - --holesky
      - --datadir=/data
      - --jwt-secret=/jwtsecret
      - --p2p-host-ip={{ public_ip.content | trim }}
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --execution-endpoint=http://erigon:8551
      - --checkpoint-sync-url=https://holesky.beaconstate.info
      - --genesis-beacon-api-url=https://holesky.beaconstate.info
      - --accept-terms-of-use
      - --http-mev-relay=http://mev_boost:18550 # Lido
      # - --suggested-fee-recipient=0x34D68dFFa8cFe02Dd9C480b8bfB7C3A9ED3fc24a # Lido
