# Ethereum versions and approach
network: ethereum
folder: "{{ user_dir }}/docker-compose/{{ network }}"
# No custom_port_prefix for Ethereum

# Execution
# https://github.com/ethereum/go-ethereum/releases
execution_container_name: geth
execution_container_version: v1.14.11
execution_snapshot_location: "{{ folder }}/geth/chaindata"
execution_network: sepolia
# Consensus
# https://github.com/sigp/lighthouse/releases
consensus_container_name: lighthouse
consensus_container_version: v5.3.0
consensus_snapshot_location: "{{ folder }}/lighthouse/data"
consensus_network: sepolia
consensus_checkpoint_sync_url: https://sepolia.beaconstate.info

# Monitoring
execution_github_org: ethereum
execution_github_repo: go-ethereum
execution_rpc_port: 8545
execution_public_rpc: https://ethereum-sepolia-rpc.publicnode.com
