# Polygon versions and approach
network: testnet_optimism
folder: "{{ user_dir }}/docker-compose/{{ network }}"
custom_port_prefix: 133
consensus_port_prefix: 233

# Execution
execution_container_name: testnet-op-geth
execution_container_version: v1.101411.0
execution_snapshot_location: "{{ folder }}/op-geth/geth/chaindata"

# Consensus
consensus_container_name: testnet-op-node
consensus_container_version: v1.9.4

# Optimism specific
execution_network: op-sepolia
execution_sequencerhttp: https://sepolia-sequencer.optimism.io

consensus_network: op-sepolia
