---
- name: Copy sshd_config file
  ansible.builtin.template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: "0644"
  notify: Restart ssh

- name: Remove small Diffie-Hellman moduli
  ansible.builtin.shell: "{{ item }}"
  environment:
    PATH: "{{ path }}"
  loop:
    - "awk '$5 >= 3072' /etc/ssh/moduli > /etc/ssh/moduli.tmp"
    - "mv /etc/ssh/moduli.tmp /etc/ssh/moduli"
  notify: Restart ssh
