# Ethereum versions and approach
network: ethereum
folder: "{{ user_dir }}/docker-compose/{{ network }}"
# No custom_port_prefix for Ethereum

# Execution
# https://github.com/paradigmxyz/reth/releases
execution_container_name: reth
execution_container_version: v1.1.5
# execution_snapshot_location: "{{ folder }}/reth/geth/nodes"
execution_network: mainnet

# Consensus
# https://github.com/sigp/lighthouse/releases
consensus_container_name: lighthouse
consensus_container_version: v6.0.1
# consensus_snapshot_location: "{{ folder }}/lighthouse/mainnet/beacon"
consensus_network: mainnet
consensus_checkpoint_sync_url: https://sync-mainnet.beaconcha.in

# Monitoring
execution_github_org: ethereum
execution_github_repo: go-ethereum
execution_rpc_port: 8545
execution_public_rpc: https://ethereum-rpc.publicnode.com
