# Gnosis
network: kroma
folder: "{{ user_dir }}/docker-compose/kroma-data"
custom_port_prefix: 146

# Monitoring
execution_github_org: kroma-network
execution_github_repo: go-ethereum
execution_public_rpc: https://api.kroma.network
