# Kroma Network using Optimism Stack playbook
# Port prefix: 146
# Docs:

network: kroma
folder: "{{ user_dir }}/docker-compose/{{ network }}"
custom_port_prefix: 146

# Execution
# https://github.com/ethereum-optimism/op-geth
execution_container_name: kroma-geth
execution_container_version: v0.6.1
execution_container_image: kromanetwork/geth
execution_genesis: https://raw.githubusercontent.com/kroma-network/kroma-up/refs/heads/main/config/mainnet/genesis.json
execution_syncmode: full
execution_bootnodes: "enode://acf4af39e9d9f3bbdb700315fde6e909efc714bd9a012b0f6943c4f9110008e3da2cb6c2ac9d3b6d98184a5ead57c4409be4ae7b19da1f554ceee7ba86c1fc2e@p2p-0.kroma.network:30304?discport=30303,enode://a3b6a7087b3399eefdb1ce5870aa0e58a60bfeccf3f7f7c02f5e142b1a544d19c171f7688d08db786d5e9b3ba734482bf8cf29dab7d46917b9da7f61656fde39@p2p-1.kroma.network:30304?discport=30303"

# Consensus
# https://github.com/ethereum-optimism/optimism
consensus_container_name: kroma-node
consensus_container_image: kromanetwork/node
consensus_container_version: v2.1.1
consensus_rollup: https://raw.githubusercontent.com/kroma-network/kroma-up/refs/heads/main/config/mainnet/rollup.json
consensus_bootnodes: "enr:-J24QIRQ_Sxsn08UW2djuM7XIiKMqDnjIRmZV3Y82aBxI396bIligpv716MNmEDitgiNzTYLx9pWVBZUmBLGZao3cJKGAYpjUHvsgmlkgnY0gmlwhA3RbWiHb3BzdGFja4P_AQCJc2VjcDI1NmsxoQO6Fg_lxKa4bqrCTRndRjP6V0Ahh_CduFC4c4khUSiRK4N0Y3CCIyuDdWRwgiMr,enr:-J24QJ0TyKGwcMuY4PCVe7Qo77pSMMkFHMHHZG5IZTtfURttM7by94vRPmFZzlteuCESo8KQC7GxEUKtRxK9dXQpvpGGAYpjUH99gmlkgnY0gmlwhAMldxyHb3BzdGFja4P_AQCJc2VjcDI1NmsxoQJXGyNhwNUSIdGsWbLChN6a47_bfRBFlFCARgjHnl6r-YN0Y3CCIyuDdWRwgiMr"
consensus_options:
  rollup.config: "/rollup.json"

# Monitoring
execution_github_org: kroma-network
execution_github_repo: go-ethereum
execution_public_rpc: https://api.kroma.network
