# Optimism versions and approach
network: optimism
folder: "{{ user_dir }}/docker-compose/{{ network }}"
custom_port_prefix: 133
consensus_port_prefix: 233

# Execution
# https://github.com/ethereum-optimism/op-geth
execution_container_name: op-geth
execution_container_version: v1.101411.6
execution_snapshot_location: "{{ folder }}/op-geth/geth/chaindata"

# Consensus
# https://github.com/ethereum-optimism/optimism
consensus_container_name: op-node
consensus_container_version: v1.10.3

# Optimism specific
execution_network: op-mainnet
execution_sequencerhttp: https://mainnet-sequencer.optimism.io

consensus_network: op-mainnet

# Monitoring
execution_github_org: ethereum-optimism
execution_github_repo: op-geth
execution_public_rpc: https://optimism-rpc.publicnode.com
