---
- name: Change hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: debian

- name: Set timezone to UTC
  community.general.timezone:
    name: Etc/UTC

- name: Update hosts file
  ansible.builtin.template:
    src: etc_hosts.j2
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Update limits for user
  ansible.builtin.blockinfile:
    path: /etc/security/limits.conf
    insertbefore: "# End of file"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      {{ ansible_user }} soft nofile 1048576
      {{ ansible_user }} hard nofile 1048576
      {{ ansible_user }} soft nproc 1048576
      {{ ansible_user }} hard nproc 1048576

- name: Update logrotate.conf
  ansible.builtin.template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart logrotate

- name: Add noisy journald.conf
  ansible.builtin.template:
    src: "journald@noisy.j2"
    dest: "/etc/systemd/journald@noisy.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart journald

#### Performance tuning
#
# Tuned profile (cpu governor, disk scheduler, etc)
- name: Retrieve tuned profile
  ansible.builtin.slurp:
    src: "/etc/tuned/active_profile"
  register: active_profile

- name: Set tuned profile
  ansible.builtin.command: "/usr/sbin/tuned-adm profile {{ tuned }}"
  when: active_profile.content | b64decode | trim != tuned

# Memory and swap tuning
- name: Set swappiness to 10
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "10"
    state: present
    reload: true

- name: Set vm.vfs_cache_pressure to 50
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: "50"
    state: present
    reload: true

# Network tuning
- name: Set default queuing discipline to fq
  ansible.posix.sysctl:
    name: net.core.default_qdisc
    value: "fq"
    state: present
    reload: true

- name: Set default congestion control to bbr
  ansible.posix.sysctl:
    name: net.ipv4.tcp_congestion_control
    value: "bbr"
    state: present
    reload: true
