---
- name: Install required packages for user setup
  ansible.builtin.apt:
    name:
      - sudo
      - zsh
      - git
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Create ansible user, password
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: "{{ password }}"
    state: present
    shell: /bin/zsh

- name: Set authorized keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  loop:
    - "{{ ssh_pubkey1 }}"
    - "{{ ssh_pubkey2 }}"

- name: Allow sudo
  ansible.builtin.copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD: ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}"
    owner: "root"
    group: "root"
    mode: "0440"

- name: Capture files in sudoers for deletion
  ansible.builtin.find:
    paths: "/etc/sudoers.d"
    file_type: file
    excludes:
      - "{{ ansible_user }}"
      - "zabbix"
      - "README"
  register: found_files

- name: Delete extra users in sudoers
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ found_files['files'] }}"

- name: Set ansible_user specific tools
  become: false
  block:
    - name: Create .screenrc
      ansible.builtin.template:
        src: screenrc.j2
        dest: "/home/{{ ansible_user }}/.screenrc"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Clone ohmyz.sh
      ansible.builtin.git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: "{{ user_dir }}/.oh-my-zsh"
        version: "master"
        single_branch: true
        update: true
        force: true

    - name: Copy .zshrc config
      ansible.builtin.template:
        src: "zshrc.j2"
        dest: "{{ user_dir }}/.zshrc"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Add honukai theme
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/oskarkrawczyk/honukai-iterm/master/honukai.zsh-theme"
        dest: "{{ user_dir }}/.oh-my-zsh/custom/themes/"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Add zsh-autosuggestion
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: "{{ user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        version: "master"
        single_branch: true
        update: true

    - name: Add TOML vim plugin
      ansible.builtin.git:
        repo: "https://github.com/cespare/vim-toml.git"
        dest: "{{ user_dir }}/.vim/pack/plugins/start/vim-toml"
        single_branch: true
        version: "main"
        update: true

    - name: Create source folder in home directory
      ansible.builtin.file:
        path: "{{ user_dir }}/source"
        state: directory
        mode: "0755"
