---
- name: Install universal essentials
  ansible.builtin.apt:
    name:
      - logrotate
      - ufw
      - chrony
      - htop
      - screen
      - build-essential
      - wget
      - curl
      - fio
      - vim
      - jq
      - tree
      - bc
      - prometheus-node-exporter
      - lz4
      - aria2
      - zip
      - net-tools
      - tuned
      - tuned-utils
      - tuned-utils-systemtap
      - tmux
      - vlan
      - nvme-cli
      - bash-completion
      - lsof
      - rsync
      - mdadm
      - dnsutils
      - apparmor-utils
      - lshw
      - bonnie++
      - bwm-ng
      - iotop
      - zstd
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install Debian essentials
  when: ansible_distribution == "Debian"
  ansible.builtin.apt:
    name:
      - firmware-linux-nonfree
    state: present

- name: Install Ubuntu essentials
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    name:
      - "linux-generic-hwe-{{ ansible_distribution_version }}"
    state: present

- name: Remove ipmi related tools
  ansible.builtin.apt:
    name:
      - ipmitools
      - openipmi
      - freeipmi
    state: absent
    purge: true
    autoremove: true
