---
- name: Install universal essentials
  ansible.builtin.apt:
    name:
      - logrotate
      - ufw
      - chrony
      - htop
      - screen
      - build-essential
      - wget
      - curl
      - fio
      - vim
      - jq
      - tree
      - bc
      - prometheus-node-exporter
      - lz4
      - aria2
      - zip
      - net-tools
      - tuned
      - tuned-utils
      - tuned-utils-systemtap
      - tmux
      - vlan
      - nvme-cli
      - bash-completion
      - lsof
      - rsync
      - mdadm
      - dnsutils
      - apparmor-utils
      - lshw
      - bonnie++
      - bwm-ng
      - iotop
      - zstd
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install Debian essentials
  when: ansible_distribution == "Debian"
  ansible.builtin.apt:
    name:
      - firmware-linux-nonfree
    state: present

- name: Install Ubuntu essentials
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    name:
      - "linux-generic-hwe-{{ ansible_distribution_version }}"
    state: present

- name: Remove ipmi related tools
  ansible.builtin.apt:
    name:
      - ipmitools
      - openipmi
      - freeipmi
    state: absent
    purge: true
    autoremove: true

# Set timezone to UTC
- name: Set timezone to UTC
  community.general.timezone:
    name: Etc/UTC

- name: Retrieve tuned profile
  ansible.builtin.slurp:
    src: "/etc/tuned/active_profile"
  register: active_profile

- name: Set tuned profile
  ansible.builtin.command: "/usr/sbin/tuned-adm profile {{ tuned }}"
  when: active_profile.content | b64decode | trim != tuned

- name: Set swappiness to 10
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "10"
    state: present
    reload: true

- name: Set vm.vfs_cache_pressure to 50
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: "50"
    state: present
    reload: true

- name: Add TOML vim plugin
  become: false
  ansible.builtin.git:
    repo: "https://github.com/cespare/vim-toml.git"
    dest: "{{ user_dir }}/.vim/pack/plugins/start/vim-toml"
    single_branch: true
    version: "main"

- name: Create source folder in home directory
  become: false
  ansible.builtin.file:
    path: "{{ user_dir }}/source"
    state: directory
    mode: "0755"
