---
- name: Check for mc binary
  ansible.builtin.stat:
    path: /usr/local/bin/mc
    checksum_algorithm: sha256
  register: mc_ver

- name: Set fact based on architecture
  ansible.builtin.set_fact:
    mc_download_url: "https://dl.min.io/client/mc/release/linux-{% if ansible_architecture == 'aarch64' %}arm64{% else %}amd64{% endif %}"

- name: Get sha256 of download
  ansible.builtin.uri:
    url: "{{ mc_download_url }}/mc.sha256sum"
    return_content: true
  register: url_output

- name: Set fact
  ansible.builtin.set_fact:
    mc_sha256: "{{ url_output.content.split(' ')[0] }}"

- name: Install mc client
  when: (not mc_ver.stat.exists) or (mc_sha256 != mc_ver.stat.checksum)
  become: true
  ansible.builtin.get_url:
    url: "{{ mc_download_url }}/mc"
    dest: /usr/local/bin/mc
    mode: "0755"
    checksum: sha256:{{ mc_sha256 }}

- name: Force snapshots alias
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.command: /usr/local/bin/mc alias set snapshots {{ mc_url }} {{ mc_access_key }} {{ mc_secret_key }}
