---
- name: Uniform sources
  ansible.builtin.include_role:
    name: init_bare
    tasks_from: update_sources

- name: Create users
  ansible.builtin.include_tasks: create_users.yml

- name: Configure machine
  ansible.builtin.import_tasks: configure_machine.yml

- name: Install essentials
  ansible.builtin.import_tasks: install_essentials.yml

- name: Install mc
  ansible.builtin.import_tasks: install_mc.yml

- name: Install promtail
  ansible.builtin.import_tasks: install_promtail.yml
