---
- name: Configure Chainlink components
  ansible.builtin.import_tasks: update_chainlink.yml

- name: Configure OTel Collector
  ansible.builtin.import_tasks: update_otel.yml

- name: Configure External Adapter versions
  ansible.builtin.import_tasks: update_external_adapters.yml

- name: Run docker-compose updates
  ansible.builtin.import_tasks: update_docker_compose.yml
