---
- name: Define statesync rpc
  ansible.builtin.set_fact:
    statesync_rpc: "{% if snap_rpc is defined %}{{ snap_rpc }}{% else %}https://rpc.cosmos.directory:443/{{ network }}{% endif %}"

- name: Create state_sync directory
  ansible.builtin.file:
    path: "{{ user_dir }}/state_sync"
    state: directory
    mode: "0755"

- name: Copy state_sync file
  ansible.builtin.template:
    src: "state_sync.sh.j2"
    dest: "{{ user_dir }}/state_sync/state_sync_{{ network }}.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"
