---
- name: Set facts for memory limits # 32GB (75%/85%), 64GB (80%/88%), 128GB (85%/90%)
  ansible.builtin.set_fact:
    memory_high_mb: >-
      {%- if ansible_memory_mb.real.total < 32768 -%}
        {{ (ansible_memory_mb.real.total * 0.75) | round | int }}
      {%- elif ansible_memory_mb.real.total < 65536 -%}
        {{ (ansible_memory_mb.real.total * 0.80) | round | int }}
      {%- else -%}
        {{ (ansible_memory_mb.real.total * 0.85) | round | int }}
      {%- endif -%}
    memory_max_mb: >-
      {%- if ansible_memory_mb.real.total < 32768 -%}
        {{ (ansible_memory_mb.real.total * 0.85) | round | int }}
      {%- elif ansible_memory_mb.real.total < 65536 -%}
        {{ (ansible_memory_mb.real.total * 0.88) | round | int }}
      {%- else -%}
        {{ (ansible_memory_mb.real.total * 0.90) | round | int }}
      {%- endif -%}

- name: Install cosmovisor
  ansible.builtin.shell: "go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@{{ cosmovisor_version }}"
  environment:
    PATH: "/usr/local/go/bin"
    GOPATH: "{{ user_dir }}/go"

- name: Create Cosmovisor directories for binary
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ user_dir }}/{{ folder }}/cosmovisor/genesis/bin"
    - "{{ user_dir }}/{{ folder }}/cosmovisor/upgrades"

- name: Copy cosmovisor systemctl service file for binary
  become: true
  ansible.builtin.template:
    src: "cosmovisor.service.j2"
    dest: "/etc/systemd/system/{{ daemon }}.service"
    owner: root
    group: root
    mode: "0644"

- name: Enable cosmovisor service for binary
  become: true
  ansible.builtin.systemd:
    name: "{{ daemon }}"
    daemon_reload: true
    enabled: true
